# Generated by Django 4.2.30 on 2026-05-31 21:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('broker', models.CharField(blank=True, max_length=100, verbose_name='Broker')),
                ('account_type', models.CharField(choices=[('Live', 'Live'), ('Challange', 'Challenge (Prop Firm)'), ('Backtest', 'Backtest'), ('Demo', 'Demo')], default='Live', max_length=20, verbose_name='Tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Balance inicial ($)')),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Meta ($)')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de trading',
                'verbose_name_plural': 'Modelos de trading',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('entry_date', models.DateField(verbose_name='Fecha entrada')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Hora entrada')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Fecha salida')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora salida')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (min)')),
                ('status', models.CharField(choices=[('Open', 'Open 🟡'), ('Closed', 'Closed ✅')], default='Open', max_length=10, verbose_name='Estado')),
                ('is_backtest', models.BooleanField(default=False, verbose_name='¿Es backtest?')),
                ('bias', models.CharField(blank=True, choices=[('Bullish', 'Bullish 🟢'), ('Bearish', 'Bearish 🔴'), ('Neutral', 'Neutral ⚪')], max_length=10, verbose_name='Bias')),
                ('market_conditions', models.CharField(blank=True, choices=[('Strong uptrend (LTF)', 'Strong Uptrend (LTF)'), ('Pullback in uptrend', 'Pullback in Uptrend'), ('Strong downtrend (LTF)', 'Strong Downtrend (LTF)'), ('Pullback in downtrend', 'Pullback in Downtrend'), ('Consolidation before reversal', 'Consolidation Before Reversal'), ('Ranging market', 'Ranging Market'), ('High volatility', 'High Volatility')], max_length=60, verbose_name='Condiciones de mercado')),
                ('session', models.CharField(blank=True, choices=[('London Open', 'London Open'), ('London', 'London'), ('London Close', 'London Close'), ('New York', 'New York'), ('New York AM', 'New York AM'), ('New York PM', 'New York PM'), ('Asian', 'Asian'), ('Asian Open', 'Asian Open')], max_length=20, verbose_name='Sesión')),
                ('news_impact', models.CharField(blank=True, choices=[('Low', 'Low 🟢'), ('Medium', 'Medium 🟡'), ('High', 'High 🔴'), ('None', 'No News')], max_length=10, verbose_name='Impacto noticias')),
                ('entry_timeframe', models.CharField(blank=True, choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('1 Hour', '1 Hour'), ('4 Hours', '4 Hours'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=20, verbose_name='Timeframe entrada')),
                ('entry_signal', models.CharField(blank=True, max_length=50, verbose_name='Señal de entrada')),
                ('order_type', models.CharField(blank=True, choices=[('Limit Order', 'Limit Order'), ('Market Order', 'Market Order'), ('Stop Order', 'Stop Order')], max_length=20, verbose_name='Tipo de orden')),
                ('position', models.CharField(blank=True, choices=[('Buy', 'Buy  ▲'), ('Sell', 'Sell ▼')], max_length=4, verbose_name='Posición')),
                ('type_of_trade', models.CharField(blank=True, choices=[('Scalping', 'Scalping'), ('Day Trade', 'Day Trade'), ('Short Term Trade', 'Short Term Trade'), ('Swing Trade', 'Swing Trade')], max_length=20, verbose_name='Tipo de trade')),
                ('setup_grade', models.CharField(blank=True, choices=[('A+', 'A+ ⭐'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D — No Setup')], max_length=5, verbose_name='Calidad del setup')),
                ('confluences', models.TextField(blank=True, verbose_name='Confluencias')),
                ('key_levels', models.TextField(blank=True, verbose_name='Niveles clave')),
                ('risk_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Riesgo (%)')),
                ('sl_pips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='S/L Pips')),
                ('sl_management', models.CharField(blank=True, choices=[('Moved to BE', 'Moved to BE'), ('Locked Profit', 'Locked Profit'), ('Trailing Stop', 'Trailing Stop'), ('Full Stop Loss', 'Full Stop Loss'), ('Manual Close', 'Manual Close')], max_length=20, verbose_name='Gestión del SL')),
                ('tp_management', models.TextField(blank=True, verbose_name='Gestión del TP')),
                ('outcome', models.CharField(blank=True, choices=[('maximum_profit', '🚀 Maximum Profit!'), ('great_exit', '✅ Great Exit!'), ('good_exit', '🎯 Good Exit'), ('winner_to_be', '⚠️ Winner to BE but Fees Lost'), ('capital_protected', '🔵 Capital Protected'), ('winning_turned_loser', '💔 Winning Trade Turned Loser'), ('stop_loss', '❌ Stop Loss'), ('partial_win', '🟡 Partial Win')], max_length=30, verbose_name='Resultado')),
                ('actual_rr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='RR conseguido')),
                ('max_rr_reached', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='RR máx. alcanzado')),
                ('gross_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gross PnL ($)')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Fees ($)')),
                ('net_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Net PnL ($)')),
                ('mistakes', models.TextField(blank=True, verbose_name='Errores cometidos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trades.account', verbose_name='Cuenta')),
                ('trading_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trades.tradingmodel', verbose_name='Modelo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-entry_date', '-entry_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterActionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('went_well', models.TextField(blank=True, verbose_name='¿Qué salió bien?')),
                ('went_wrong', models.TextField(blank=True, verbose_name='¿Qué salió mal?')),
                ('improvement', models.TextField(blank=True, verbose_name='¿Qué mejorar?')),
                ('lesson', models.TextField(blank=True, verbose_name='Lección aprendida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='after_action_report', to='trades.trade')),
            ],
            options={
                'verbose_name': 'After-Action Report',
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'entry_date'], name='trades_trad_user_id_82a273_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'symbol'], name='trades_trad_user_id_089547_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'outcome'], name='trades_trad_user_id_a83657_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'entry_date'], name='trades_trad_account_026ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'is_backtest'], name='trades_trad_user_id_65e9bf_idx'),
        ),
    ]
