# Generated by Django 6.0.3 on 2026-03-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('setup', models.CharField(blank=True, max_length=5, verbose_name='Setup')),
                ('date_from', models.DateField(verbose_name='Fecha inicio')),
                ('date_to', models.DateField(verbose_name='Fecha fin')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance inicial')),
                ('risk_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Riesgo (%)')),
                ('results_json', models.TextField(blank=True, verbose_name='Resultados JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
                'ordering': ['-created_at'],
            },
        ),
    ]
